### ISSUE TITLE
Library cleanup

### ISSUE THREAD

**Issue by brandur-stripe** [stripe/stripe-go#449]
During the review of #446, quite a few possibilities for improvements and cleanup of the library came up. Here's the list:

* [x] ~~Remove `Email` from token.go now that Stripe Checkout doesn't seem to use this library anymore.~~ (Actually, still in use.)
* [x] Remove `Display` function `BankAccount` and the like. It doesn't add very much (see #451).
* [ ] Move ChargeParam.Fraud to be its own subparameter struct called something like `FraudDetails` (see #452).
* [ ] Drop recipients entirely given that it's all deprecated (and drop `form`'s `AppendToPrefixed` which is only needed for recipients).
* [ ] Optimize performance of the `form` package's `AppendTo` (see `BenchmarkAppendTo` for help with this).
* [x] Order all parameter and resource struct fields alphabetically (see #450).
* [ ] Replace weird truncates (e.g. `Src`) with expanded words (e.g. `Source`). These should be as close to the name of the API field/param as much as possible for least confusion.
* [ ] Get rid of all "shared" parameter/resource structs. There should be no structs that have fields annotated with both `json` and `form` tags.

**Comment by brandur-stripe** [comment]
@remi-stripe Doh. I was wrong about Checkout no longer using this library. The JS bundle itself doesn't of course, but its backend API still appears to. Unfortunately we won't be able to remove `Email` for now.

**Comment by brandur-stripe** [comment]
Alright most of these are done, and I've opened two new fields (#456 and #457) for those that weren't.
